USE DATABASE scorpion_and_seal_project_db;
USE SCHEMA LABSKUSKA;
USE WAREHOUSE SEAL_WH;

-- 1 - Uzatváranie eura v pondelok (jeseň 2008)
SELECT
    ROW_NUMBER() OVER (ORDER BY d.DATE) AS MONDAY_NUMBER,
    d.DOW_NAME,
    f.CLOSE,
    d.DATE
FROM FACT_FOREX f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE f.CURRENCY_ID = 31 AND d.YEAR = 2008 AND d.DOW = 2 AND d.SEASON = 'Autumn'
ORDER BY d.DATE;

-- 2 - Rast hrivny voči doláru (2006 – 2024)
SELECT
    c.COUNTRY_NAME,
    d.YEAR,
    MAX(f.CLOSE) AS MAX_CLOSE
FROM FACT_FOREX f
JOIN DIM_COUNTRY c ON f.COUNTRY_ID = c.COUNTRY_ID
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE f.CURRENCY_ID = 105 AND d.YEAR BETWEEN 2005 AND 2024
GROUP BY c.COUNTRY_NAME, d.YEAR
ORDER BY c.COUNTRY_NAME, d.YEAR;

-- 3 - Rozsah výmenných kurzov pre Top 21 (nie Top 7/Top 5) pre rok 2024
WITH middle_currencies AS (
    SELECT CURRENCY_ID, CURRENCY AS CURRENCY_NAME
    FROM DIM_CURRENCY
    WHERE G21 = TRUE
      AND G7 = FALSE
      AND TOP5 = FALSE
)
SELECT
    c.CURRENCY_NAME,
    MAX(f.CLOSE) - MIN(f.CLOSE) AS CLOSE_RANGE_2024
FROM FACT_FOREX f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
JOIN middle_currencies c ON f.CURRENCY_ID = c.CURRENCY_ID
WHERE d.YEAR = 2024
GROUP BY c.CURRENCY_NAME
ORDER BY CLOSE_RANGE_2024 DESC;

-- 4 - Výmenný kurz v Arménsku pre rok 2025 (zima a leto)
SELECT 
    d.SEASON, 
    MIN(f.CLOSE) AS MIN_CURRENCY, 
    MAX(f.CLOSE) AS MAX_CURRENCY
FROM FACT_FOREX f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
JOIN DIM_COUNTRY c ON f.COUNTRY_ID = c.COUNTRY_ID
WHERE c.COUNTRY_NAME = 'Armenia' AND d.YEAR = 2024 AND d.SEASON IN ('Winter', 'Summer')
GROUP BY d.SEASON
ORDER BY d.SEASON;

-- 5 - min + max výmenné kurzy (BGN) medzi aktívnymi menami (obdobie 2020 – 2025).
WITH BGN_ACTIVE AS (
    SELECT 
        f.OPEN,
        d.DATE
    FROM FACT_FOREX f
    JOIN DIM_CURRENCY c ON f.CURRENCY_ID = c.CURRENCY_ID
    JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
    WHERE c.CURRENCY = 'BGN' AND f.STATUS_ID = 2 AND d.YEAR BETWEEN 2020 AND 2025
)
SELECT
    'MIN' AS TYPE,
    OPEN AS CURRENCY,
    DATE AS DATE_VALUE
FROM BGN_ACTIVE
QUALIFY OPEN = MIN(OPEN) OVER ()

UNION ALL

SELECT
    'MAX' AS TYPE,
    OPEN AS CURRENCY,
    DATE AS DATE_VALUE
FROM BGN_ACTIVE
QUALIFY OPEN = MAX(OPEN) OVER ();

-- 6 - Priemerná miera otvorenia eura podľa sezóny za rok 2024.
SELECT
    d.SEASON,
    ROUND(AVG(f.OPEN), 2) AS AVG_OPEN
FROM FACT_FOREX f
JOIN DIM_CURRENCY c ON f.CURRENCY_ID = c.CURRENCY_ID
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
WHERE c.TOP5 = TRUE AND c.CURRENCY = 'EUR' AND d.YEAR = 2024 AND f.STATUS_ID = 2
GROUP BY d.SEASON
ORDER BY d.SEASON;