-- CREATE DB AND SCHEMA
CREATE DATABASE SCORPION_AND_SEAL_PROJECT_DB;
USE DATABASE SCORPION_AND_SEAL_PROJECT_DB;
CREATE OR REPLACE SCHEMA labSKUSKA;
USE SCHEMA labSKUSKA;


-- STAGING TABLE -> CRYPTO_CURRENCY_HISTORICAL_DATA
CREATE OR REPLACE TABLE STG_CRYPTO_CURRENCY_HISTORICAL_DATA AS
SELECT
    CURRENCY,
    BASE,
    CAST(TIMESTAMP AS DATE) AS PRICE_DATE,
    OPEN,
    CLOSE,
    HIGH,
    LOW,
    VOLUME
FROM FEDERAL_EXCHANGE_RATES.INSIGHTS.CRYPTO_CURRENCY_HISTORICAL_DATA;

-- STAGING TABLE -> FOREIGN_EXCHANGE_RATE
CREATE OR REPLACE TABLE STG_FOREIGN_EXCHANGE_RATE AS
SELECT *
FROM FEDERAL_EXCHANGE_RATES.INSIGHTS.FOREIGN_EXCHANGE_RATE
WHERE TIME IS NOT NULL;

ALTER TABLE STG_FOREIGN_EXCHANGE_RATE DROP COLUMN S_NO;


-- STAGING TABLE -> FOREIGN_EXCHANGE_RATES_TRENDS
CREATE OR REPLACE TABLE STG_FOREIGN_EXCHANGE_RATES_TRENDS AS
SELECT *
FROM FEDERAL_EXCHANGE_RATES.INSIGHTS.FOREIGN_EXCHANGE_RATES_TRENDS;


-- STAGING TABLE -> G21_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATE
CREATE OR REPLACE TABLE STG_G21_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATE AS
SELECT
    ARGENTINE_PESO              AS ARS,
    AUSTRALIAN_DOLLAR           AS AUD,
    BRAZIL_REAL                 AS BRL,
    CANADIAN_DOLLAR             AS CAD,
    CENTRAL_AFRICAN_CFA_FRANC   AS XAF,
    CHINA_YUAN                  AS CNY,
    EURO_AREA_EURO              AS EUR,
    INDIAN_RUPEE                AS INR,
    INDONESIAN_RUPIAH           AS IDR,
    JAPAN_YEN                   AS JPY,
    KOREAN_WON                  AS KRW,
    MEXICAN_PESO                AS MXN,
    RUSSIAN_RUBLE               AS RUB,
    SAUDI_RIYAL                 AS SAR,
    SOUTH_AFRICA_RAND           AS ZAR,
    TURKISH_LIRA                AS TRY,
    UNITED_KINGDOM_POUND        AS GBP,
    DATE
FROM FEDERAL_EXCHANGE_RATES.INSIGHTS.G21_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATE;


-- STAGING TABLE -> G7_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATES
CREATE OR REPLACE TABLE STG_G7_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATES AS
SELECT
    CANADIAN_DOLLAR AS CAD,
    EURO_AREA_EURO AS EUR,
    JAPAN_YEN AS JPY,
    RUSSIAN_RUBLE AS RUB,
    UNITED_KINGDOM_POUND AS GBP,
    DATE
FROM FEDERAL_EXCHANGE_RATES.INSIGHTS.G7_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATES;


-- STAGING TABLE -> TOP_100_MARKET_CAP_CRYPTO
CREATE OR REPLACE TABLE STG_TOP_100_MARKET_CAP_CRYPTO AS
SELECT
    CURRENCY,
    BASE,
    CAST(TIMESTAMP AS DATE) AS PRICE_DATE,
    OPEN,
    HIGH,
    LOW,
    CLOSE,
    VOLUME
FROM FEDERAL_EXCHANGE_RATES.INSIGHTS.TOP_100_MARKET_CAP_CRYPTO_CURRENCY_HISTORICAL_DATA;


-- STAGING TABLE -> TOP_FIVE_TRADABLE_CURRENCIES
CREATE OR REPLACE TABLE STG_TOP_FIVE_TRADABLE_CURRENCIES AS
SELECT
    CANADIAN_DOLLAR AS CAD,
    EURO_AREA_EURO AS EUR,
    JAPAN_YEN AS JPY,
    UNITED_KINGDOM_POUND AS GBP,
    WITZERLAND_FRANC AS CHF,
    DATE
FROM FEDERAL_EXCHANGE_RATES.INSIGHTS.TOP_FIVE_TRADABLE_CURRENCIES_FOREIGN_EXCHANGE_RATE;


-- DATA VALIDATION QUERIES (CHECK STAGE TABLES)
SELECT
    CURRENCY,
    BASE,
    PRICE_DATE,
    ROUND(OPEN, 8) AS OPEN,
    ROUND(HIGH, 8) AS HIGH,
    ROUND(LOW, 8) AS LOW,
    ROUND(CLOSE, 8) AS CLOSE,
    ROUND(VOLUME, 8) AS VOLUME
FROM STG_CRYPTO_CURRENCY_HISTORICAL_DATA;
SELECT * FROM STG_FOREIGN_EXCHANGE_RATE ORDER BY TIME DESC;
SELECT * FROM STG_FOREIGN_EXCHANGE_RATES_TRENDS;
SELECT * FROM STG_G21_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATE;
SELECT * FROM STG_G7_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATES;
SELECT * FROM STG_TOP_100_MARKET_CAP_CRYPTO;
SELECT * FROM STG_TOP_FIVE_TRADABLE_CURRENCIES;


-- ELT - (T)ransform
-- DIM TABLE -> DATE
CREATE OR REPLACE TABLE DIM_DATE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY DATE) AS DATE_ID,
    DATE AS DATE,
    DATE_PART(day, DATE) AS DAY,
    DATE_PART(dow, DATE) + 1 AS DOW,
    CASE DATE_PART(dow, DATE) + 1
        WHEN 1 THEN 'Monday'
        WHEN 2 THEN 'Tuesday'
        WHEN 3 THEN 'Wednesday'
        WHEN 4 THEN 'Thursday'
        WHEN 5 THEN 'Friday'
        WHEN 6 THEN 'Saturday'
        WHEN 7 THEN 'Sunday'
    END AS DOW_NAME,
    DATE_PART(month, DATE) AS MONTH,
    DATE_PART(year, DATE) AS YEAR,
    DATE_PART(quarter, DATE) AS QUARTER
FROM (
    SELECT DISTINCT DATE
    FROM STG_FOREIGN_EXCHANGE_RATES_TRENDS
    WHERE DATE IS NOT NULL
) AS unique_dates
ORDER BY DATE;


-- DIM TABLE -> CURRENCY
CREATE OR REPLACE TABLE DIM_CURRENCY AS
WITH top5 AS (
    SELECT COLUMN_NAME AS CURRENCY
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'STG_TOP_FIVE_TRADABLE_CURRENCIES'
      AND COLUMN_NAME <> 'DATE'
),
g21 AS (
    SELECT COLUMN_NAME AS CURRENCY
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'STG_G21_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATE'
      AND COLUMN_NAME <> 'DATE'
),
g7 AS (
    SELECT COLUMN_NAME AS CURRENCY
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'STG_G7_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATES'
      AND COLUMN_NAME <> 'DATE'
)
SELECT
    ROW_NUMBER() OVER (ORDER BY f.CURRENCY) AS CURRENCY_ID,
    f.CURRENCY,
    f.DESCRIPTION,
    CASE WHEN f.CURRENCY IN (SELECT CURRENCY FROM top5) THEN TRUE ELSE FALSE END AS TOP5,
    CASE WHEN f.CURRENCY IN (SELECT CURRENCY FROM g21) THEN TRUE ELSE FALSE END AS G21,
    CASE WHEN f.CURRENCY IN (SELECT CURRENCY FROM g7) THEN TRUE ELSE FALSE END AS G7
FROM (
    SELECT DISTINCT CURRENCY, DESCRIPTION
    FROM STG_FOREIGN_EXCHANGE_RATES_TRENDS
    WHERE CURRENCY IS NOT NULL
) AS f
ORDER BY f.CURRENCY;


-- DIM TABLE -> COUNTRY
CREATE OR REPLACE TABLE DIM_COUNTRY AS
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTRY) AS COUNTRY_ID,
    COUNTRY AS COUNTRY_NAME
FROM (
    SELECT DISTINCT COUNTRY
    FROM STG_FOREIGN_EXCHANGE_RATES_TRENDS
    WHERE COUNTRY IS NOT NULL
) AS unique_countries;


-- DIM TABLE -> STATUS
CREATE OR REPLACE TABLE DIM_STATUS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY ISACTIVE) AS STATUS_ID,
    ISACTIVE AS STATUS_FLAG,
    CASE
        WHEN ISACTIVE = TRUE  THEN 'ACTIVE'
        WHEN ISACTIVE = FALSE THEN 'NO ACTIVE'
        ELSE 'UNKNOWN'
    END AS STATUS_NAME
FROM (
    SELECT DISTINCT ISACTIVE
    FROM STG_FOREIGN_EXCHANGE_RATES_TRENDS
) AS unique_status;


-- FACT TABLE -> FOREX
CREATE OR REPLACE TABLE FACT_FOREX AS
SELECT
    ROW_NUMBER() OVER (ORDER BY f.DATE, f.CURRENCY, f.COUNTRY) AS FACT_ID,
    d_date.DATE_ID,
    d_currency.CURRENCY_ID,
    d_country.COUNTRY_ID,
    d_status.STATUS_ID,
    f.OPEN,
    f.CLOSE,
    f.HIGH,
    f.LOW,
    f.CLOSE - LAG(f.CLOSE) OVER (
        PARTITION BY f.CURRENCY
        ORDER BY f.DATE
    ) AS CLOSE_DIFF,
    f.CLOSE - LEAD(f.CLOSE) OVER (
        PARTITION BY f.CURRENCY
        ORDER BY f.DATE
    ) AS NEXT_CLOSE_DIFF,
    AVG(f.CLOSE) OVER (
        PARTITION BY f.CURRENCY, f.COUNTRY
        ORDER BY f.DATE
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS AVG_LAST_7_DAYS
FROM STG_FOREIGN_EXCHANGE_RATES_TRENDS f
LEFT JOIN DIM_DATE     d_date     ON f.DATE     = d_date.DATE
LEFT JOIN DIM_CURRENCY d_currency ON f.CURRENCY = d_currency.CURRENCY
LEFT JOIN DIM_COUNTRY  d_country  ON f.COUNTRY  = d_country.COUNTRY_NAME
LEFT JOIN DIM_STATUS   d_status   ON f.ISACTIVE = d_status.STATUS_FLAG
WHERE f.CURRENCY IS NOT NULL
  AND f.DATE IS NOT NULL
  AND f.COUNTRY IS NOT NULL;


-- DATA VALIDATION QUERIES (CHECK DIM/FACT TABLES)
SELECT * FROM DIM_DATE;
SELECT * FROM DIM_CURRENCY;
SELECT * FROM DIM_COUNTRY;
SELECT * FROM DIM_STATUS;
SELECT * FROM FACT_FOREX;


-- DROP STAGGING TABLES
DROP TABLE IF EXISTS STG_CRYPTO_CURRENCY_HISTORICAL_DATA;
DROP TABLE IF EXISTS STG_FOREIGN_EXCHANGE_RATE;
DROP TABLE IF EXISTS STG_FOREIGN_EXCHANGE_RATES_TRENDS;
DROP TABLE IF EXISTS STG_G21_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATE;
DROP TABLE IF EXISTS STG_G7_COUNTRY_CURRENCIES_FOREIGN_EXCHANGE_RATES;
DROP TABLE IF EXISTS STG_TOP_100_MARKET_CAP_CRYPTO;
DROP TABLE IF EXISTS STG_TOP_FIVE_TRADABLE_CURRENCIES;